version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_ADDR=db:6379
      - DB_PASS=
      - APP_PORT=8000
      - DOMAIN=localhost:3000
      - API_QUOTA=10

  db:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - .data:/data
